### ISSUE TITLE
 Error: incompatible character encodings: UTF-8 and US-ASCII

### ISSUE THREAD

**Issue by bxlkm** [cloudfoundry/cf-mysql-release#167] opened 2017-06-21 03:18 UTC
cf-mysql-release-v35    ruby 2.3.3p222   bosh-version 2.0.24

03:05:34 | Deprecation: Ignoring cloud config. Manifest contains 'networks' section.
03:05:34 | Preparing deployment: Preparing deployment (00:00:01)
03:05:35 | Preparing package compilation: Finding packages to compile (00:00:01)
03:05:36 | Compiling packages: cluster-schema-verifier/a2f8659250e5b51a7f5d0b0fdff5dbdc5ee98895
03:05:36 | Compiling packages: cli/8b1ad6b02cd78fc4950b7ed83d1d83c12d6a99cb
03:05:36 | Compiling packages: mysqlclient/ce95f8ac566f76b650992987d5282ee473356e43
03:05:36 | Compiling packages: golang1.7/a27a493e4ccad81a014bc98864164eb18166896a
03:05:39 | Compiling packages: cluster-schema-verifier/a2f8659250e5b51a7f5d0b0fdff5dbdc5ee98895 (00:00:03)
            L Error: incompatible character encodings: UTF-8 and US-ASCII
03:05:40 | Compiling packages: cli/8b1ad6b02cd78fc4950b7ed83d1d83c12d6a99cb (00:00:04)
            L Error: incompatible character encodings: UTF-8 and US-ASCII
03:05:40 | Compiling packages: golang1.7/a27a493e4ccad81a014bc98864164eb18166896a (00:00:04)
            L Error: incompatible character encodings: UTF-8 and US-ASCII
03:07:06 | Compiling packages: mysqlclient/ce95f8ac566f76b650992987d5282ee473356e43 (00:01:30)

03:07:15 | Error: incompatible character encodings: UTF-8 and US-ASCII

Started  Wed Jun 21 03:05:34 UTC 2017
Finished Wed Jun 21 03:07:15 UTC 2017
Duration 00:01:41

Task 89 error

**Comment by utricularian** [comment] 2017-07-06 16:41
this is a duplicate of https://github.com/cloudfoundry/cf-mysql-release/issues/169

**Closed by utricularian** 2017-07-06 16:41 UTC
Labels: scheduled
