### ISSUE TITLE
wsrep_cluster_name fixed to "cf-mariadb-galera-cluster" in arbitrator

### ISSUE THREAD

**Issue by jriguera** [cloudfoundry/cf-mysql-release#174] opened 2017-07-21 08:24 UTC
Since release V36 it is possible to customize the `wsrep_cluster_name`, but the galera arbitrator template still has fixed the value 'cf-mariadb-galera-cluster' making impossible to change, see https://github.com/cloudfoundry/cf-mysql-release/blob/master/jobs/arbitrator/templates/garbd_config.erb#L7

Thanks!

**Comment by menicosia** [comment] 2017-07-31 22:18
Hi @jriguera,

The arbitrator (as you can see) isn't something we're very focused on. We're not likely to schedule this fix in the immediate future, but would be very happy to look at a PR should you have time to submit one.

I'll close this issue for now, but as always, you can feel free to re-open if you'd like to continue the conversation!

---

Marco Nicosia
Product Manager
Pivotal Software, Inc.

**Closed by menicosia** 2017-07-31 22:18 UTC
Labels: unscheduled

**Comment by jriguera** [comment] 2017-08-01 08:12
Hi @menicosia 

Thanks for your answer!. If I manage to get enough time I will submit a PR. But, after reading your comment at https://www.pivotaltracker.com/story/show/149288119, can I would like to ask about the long term plans for the arbitrator, because we are considering setup some clusters with 2 mysql and 1 arbitrator. Can you  throw some light on that topic? (just redirect me to some dev doc/notes/plan is enough)

Thanks!

**Comment by menicosia** [comment] 2017-08-02 20:54
Hi @jriguera,

The arbitrator is a nice idea; the problem is that the most-desired path is three-node clusters. That's because Galera really works best with (at least) three copies of the data. When you only have two, and one is unavailable, it's a more anxious situation.

So, we routinely focus on, and exclusively test the three-node option. We do use the 2+1 arbitrator deployments, but not for any tests except the, "does the arbitrator work" tests. That means that bugs in optional features like this can sneak through.

Unless we hear a lot of noise from the community (about half of you are using the arbitrator, I believe), we aren't likely to put more effort into supporting the arbitrator.

All this means is that the arbitrator feature isn't deprecated, but is in the realm of "community support." We're happy to keep it in the release, but if there are minor regressions which don't affect overall functionality, we're going to rely more and more on community contributions to keep it going.

Of course we'll give PRs priority treatment whenever possible, and we can release as frequently as we'd like, so there shouldn't be a long turnaround for a final release.

Does that seem fair?

---

Marco Nicosia
Product Manager
Pivotal Software, Inc.

**Comment by jriguera** [comment] 2017-08-03 08:16
Hi @menicosia 

Yep, now I understand the reasons and I agree with you.
Thank you very much for your explanation!
